spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

catalog:
  low-stock-threshold: 2
  maximum-products: 20
  default-page-size: 5
  max-page-size: 10
